version: "3"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: test
    volumes: 
        - ./init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8002:8080
  firstlog:
    container_name: "firstlog"
    hostname: firstlog
    build:
      context: ./firstlog
    ports: 
      - 5001:80
  secondlog:
    container_name: "secondlog"
    hostname: secondlog
    build:
      context: ./secondlog
    ports: 
      - 5002:80
  loadbalancer:
    build:
      context: loadbalancer/
    ports:
      - 8080:80
    depends_on:
      - FirstLog
      - SecondLog

volumes:
  site:
